=== Nkawther/Doc-Num2020/src/main/resources/static/final.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT file (header, body)>

<!ELEMENT header (nbMsg, transmitter, receiver, authRef?, authDate?)>
<!ATTLIST header idF CDATA #REQUIRED>

<!ELEMENT nbMsg (#PCDATA)>

<!ELEMENT transmitter (#PCDATA)>
<!ATTLIST transmitter idUser CDATA #REQUIRED>

<!ELEMENT receiver (#PCDATA)>
<!ATTLIST receiver idUser CDATA #REQUIRED>

<!ELEMENT authRef (#PCDATA)>
<!ELEMENT authDate (#PCDATA)>

<!ELEMENT body (listMsg)>

<!ELEMENT listMsg (message+)>

<!ELEMENT message (dateMsg,validityDuration,(authRequest|auth|accept|deny|barter|request|donation|catRequest|cat|noCat|errorMsg))>
<!ATTLIST message idMsg CDATA #REQUIRED>

<!ELEMENT dateMsg (#PCDATA)>
<!ELEMENT validityDuration (#PCDATA)>

<!ELEMENT authRequest EMPTY>
<!ELEMENT auth (authRef, authDate)>
<!ELEMENT accept (idPropositionMsg)>
<!ELEMENT deny (idPropositionMsg, reason)>

<!ELEMENT barter (rcvObjectList, sndObjectList, idPrevMsg)>
<!ELEMENT request (rcvObjectList, idPrevMsg)>
<!ELEMENT donation (sndObjectList, idPrevMsg)>

<!ELEMENT catRequest EMPTY>
<!ELEMENT cat (idCatRequestMsg, catDate, (object)+)>
<!ELEMENT noCat (idCatRequestMsg, reason)>

<!ELEMENT errorMsg (#PCDATA)>
<!ATTLIST errorMsg idMsg CDATA #REQUIRED>
<!ATTLIST errorMsg idError CDATA #REQUIRED>

<!ELEMENT idPropositionMsg (#PCDATA)>
<!ELEMENT reason (#PCDATA)>

<!ELEMENT object (objectName, objectDetails, objectImage)>
<!ATTLIST object idObject CDATA #REQUIRED>

<!ELEMENT objectName (#PCDATA)>
<!ELEMENT objectDetails (#PCDATA)>
<!ELEMENT objectImage ANY>

<!ELEMENT catDate (#PCDATA)>
<!ELEMENT idCatRequestMsg (#PCDATA)>

<!ELEMENT sndObjectList (object)+>
<!ELEMENT rcvObjectList (object)+>

<!ELEMENT idPrevMsg (#PCDATA)>

=== Nkawther/Doc-Num2020/stylo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE file SYSTEM "final.dtd">
<file>
    <header idF="28">
        <nbMsg>4</nbMsg>
        <transmitter idUser="1">arsene</transmitter>
        <receiver idUser="23">heo</receiver>
        <authRef>81fe4bf3-088d-4386-90e7-0adc7fca007a</authRef>
        <authDate>2020-11-25 00:00:00.0</authDate>
    </header>
    <body>
        <listMsg>
            <message idMsg="29">
                <dateMsg>2020-12-10 00:00:00.0</dateMsg>
                <validityDuration>2020-12-10 00:00:00.0</validityDuration>
                <catRequest />
            </message>
            <message idMsg="30">
                <dateMsg>2020-12-10 00:00:00.0</dateMsg>
                <validityDuration>2020-12-10 00:00:00.0</validityDuration>
                <donation>
                    <sndObjectList>
                        <object>
                            <objectName>sltylo</objectName>
                            <objectDetails>bleue</objectDetails>
                            <objectImage>Any</objectImage>
                        </object>
                    </sndObjectList>
                    <idPrevMsg>27</idPrevMsg>
                </donation>
            </message>
        </listMsg>
    </body>
</file>

=== Nkawther/Doc-Num2020/src/main/resources/static/requeteAuthgr2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE file SYSTEM "final.dtd">
<file>
    <header idF="9">
        <nbMsg>1</nbMsg>
        <transmitter idUser="5">Groupe2</transmitter>
        <receiver idUser="1">Groupe1</receiver>
        <authRef>4766a8db-12c2-4321-bae0-dda86ea3f122</authRef>
        <authDate>2020-12-25 00:00:00.0</authDate>
    </header>
    <body>
        <listMsg>
            <message idMsg="10">
                <dateMsg>2020-12-25 00:00:00.0</dateMsg>
                <validityDuration>2020-12-25 00:00:00.0</validityDuration>
                <auth>
                    <authRef>2020-12-10 00:00:00.0</authRef>
                </auth>
            </message>
        </listMsg>
    </body>
</file>

=== Nkawther/Doc-Num2020/src/main/resources/static/nouveau.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE file SYSTEM "final.dtd">
<file>
    <header idF="3">
        <nbMsg>1</nbMsg>
        <transmitter idUser="1">qsdqsd</transmitter>
        <receiver idUser="2">sqdsqd</receiver>
        <authRef>77687731-4158-4390-b197-b700f452b9f4</authRef>
        <authDate>2020-12-31 00:00:00.0</authDate>
    </header>
    <body>
        <listMsg>
            <message idMsg="4">
                <dateMsg>2020-12-15 00:00:00.0</dateMsg>
                <validityDuration>2020-12-15 00:00:00.0</validityDuration>
                <cat>
                    <idCatRequestMsg>1</idCatRequestMsg>
                    <catDate>2020-12-24 00:00:00.0</catDate>
                    <object>
                        <objectName>Test1,Test2,Test3,Test4</objectName>
                        <objectDetails>Test1,Test2,Test3,Test4</objectDetails>
                        <objectImage>Any</objectImage>
                    </object>
                </cat>
            </message>
        </listMsg>
    </body>
</file>

=== Nkawther/Doc-Num2020/src/main/resources/static/file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE file SYSTEM "final.dtd">
<file>
    <header idF="1">
        <nbMsg>4</nbMsg>
        <transmitter idUser="1">Kawther</transmitter>
        <receiver idUser="2">Namane</receiver>
        <authRef>12-12-2020</authRef>
        <authDate>12-12-2020</authDate>
    </header>
    <body>
        <listMsg>
            <message idMsg="1">
                <dateMsg>12-12-2020</dateMsg>
                <validityDuration>12-12-2020</validityDuration>
                <barter>
                    <rcvObjectList>
                        <object idObject="2">
                            <objectName>kjsgdvkj</objectName>
                            <objectDetails>SecondObject</objectDetails>
                            <objectImage>Any</objectImage>
                        </object>
                    </rcvObjectList>
                    <sndObjectList>
                        <object idObject="3">
                            <objectName>jdsvjb</objectName>
                            <objectDetails>SecondObject</objectDetails>
                            <objectImage>Any</objectImage>
                        </object>
                    </sndObjectList>
                    <idPrevMsg>1</idPrevMsg>
                </barter>
            </message>
            <message idMsg="2">
                <dateMsg>11-12-2020</dateMsg>
                <validityDuration>11-12-2020</validityDuration>
                <request>
                    <rcvObjectList>
                        <object idObject="3">
                            <objectName>FisrtObject</objectName>
                            <objectDetails>SecondObject</objectDetails>
                            <objectImage>Any</objectImage>
                        </object>
                    </rcvObjectList>
                    <idPrevMsg>1</idPrevMsg>
                </request>
            </message>
            <message idMsg="3">
                <dateMsg>10-12-2020</dateMsg>
                <validityDuration>10-12-2020</validityDuration>
                <donation>
                    <sndObjectList>
                        <object idObject="4">
                            <objectName>FisrtObject</objectName>
                            <objectDetails>SecondObject</objectDetails>
                            <objectImage>Any</objectImage>
                        </object>
                    </sndObjectList>
                    <idPrevMsg>1</idPrevMsg>
                </donation>
            </message>
            <message idMsg="4">
                <dateMsg>10-12-2020</dateMsg>
                <validityDuration>10-12-2020</validityDuration>
                <cat>
                    <idCatRequestMsg>1</idCatRequestMsg>
                    <catDate>10-12-2020</catDate>
                    <object idObject="4">
                        <objectName>FisrtObject</objectName>
                        <objectDetails>SecondObject</objectDetails>
                        <objectImage>Any</objectImage>
                    </object>
                    <object idObject="5">
                        <objectName>Fisrtkjdbcqkbvk</objectName>
                        <objectDetails>SecondObject</objectDetails>
                        <objectImage>Any</objectImage>
                    </object>
                </cat>
            </message>
        </listMsg>
    </body>
</file>

=== Nkawther/Doc-Num2020/src/main/resources/static/Groupe5VersGroupe1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE file SYSTEM "final.dtd">
<file>
    <header idF="8">
        <nbMsg>1</nbMsg>
        <transmitter idUser="6">Groupe5</transmitter>
        <receiver idUser="7">Groupe1</receiver>
        <authRef />
        <authDate>2019-12-10 00:00:00.0</authDate>
    </header>
    <body>
        <listMsg>
            <message idMsg="9">
                <dateMsg>2010-12-10 00:00:00.0</dateMsg>
                <validityDuration>2020-12-10 00:00:00.0</validityDuration>
                <authRequest />
            </message>
        </listMsg>
    </body>
</file>
